### ISSUE TITLE
Searching for the number "70" does not return results in NIV or NLT

### ISSUE THREAD

**Issue by JayMJay** [Bolls-Bible/bain#11]
Searching for 100 or other numbers returns results.  If I search for "70"  (not using quotes)  it returns no results,  however ,  I know that it should return

«When Kenan was 70 years old, he became the father of Mahalalel.»

Genesis 5:12 NLT https://bolls.life/NLT/1/5/12/

**Comment by Bohooslav** [comment]
The min length for search query should be over 2 letters. In order to find that place, enter «70 years» or something like that.

Idk, if I should allow queries to be longer than 2 symbols or maybe better show message with clarification on the query requirements. What do you think?

**Comment by JayMJay** [comment]
Unless there are performance issues,  I'd change the min length  - or at least only for numbers.  Most other platforms allow it.  However, I love your site because it isn't like others.   The layout is easy to read, and I like that there are no ads.

**Comment by Bohooslav** [comment]
I like the idea to lower the length specifically for numbers. I'll try to implement it this Sunday.

**Comment by Bohooslav** [comment]
Deployed 🚀

**Comment by JayMJay** [comment]
Awesome!   Thanks for adding this.   I had stumbled on this issue because a friend and mentor was turning 70 and I was trying to find some Biblical facts about others who were 70.  Terah fathering Abraham is a big one. 
 The search was really fast.  Thanks again.
