### ISSUE TITLE
Mwanzo 6:4 SUV Translation Misquoted

### ISSUE THREAD

**Issue by okellogerald** [Bolls-Bible/bain#14]
https://bolls.life/SUV/1/6/4

Current verse: 
*Nao Wanefili?b*

Expected Verse for SUV 1997 translation: 
*Nao Wanefili walikuwako duniani siku zile; tena, baada ya hayo, wana wa Mungu walipoingia kwa binti za wanadamu, wakazaa nao wana; hao ndio waliokuwa watu hodari zamani, watu wenye sifa.*

I am just pointing that this particular verse is misquoted. And the above is its full quatation for this specific translation. I hope that helps.

**Comment by Bohooslav** [comment]
Oh, thank you for reporting. I'll try to fix it whenever I can and will
notify you. If you see anything like that again, email me and I'll take
action.
