### ISSUE TITLE
Update the href for the new repository on github

### ISSUE THREAD

**Issue by asafeclemente** [Bolls-Bible/bain#15]
At https://bolls.life/ it is currently sending to https://github.com/Bohooslav/bain/, but could it be directly the new one ?(https://github.com/Bolls-Bible/bain/)

**Comment by Bohooslav** [comment]
Oh yeah, dear. Thank you for noticing this. I'll fix it next release.

**Comment by Bohooslav** [comment]
Updated in the latest release
