### ISSUE TITLE
1 Peter 2:7 SUV Misquoted

### ISSUE THREAD

**Issue by okellogerald** [Bolls-Bible/bain#16]
https://bolls.life/ESV/60/2/7/
This verse wasn't finished in the SUV translation.

Current verse:
*Basi, heshima hii ni kwenu ninyi mnaoamini. Bali kwao wasioamini,*

Expected Verse for SUV 1997 translation:
*Basi, heshima hii ni kwenu ninyi mnaoamini. Bali kwao wasioamini, jiwe walilolikataa waashi, limekuwa jiwe kuu la pembeni.*

I hope that helps.

**Comment by Bohooslav** [comment]
Oh, sorry. I'll fix it this evening. Thanks for reporting it.

**Comment by Bohooslav** [comment]
Just released fix. Enjoy!

**Comment by okellogerald** [comment]
Thank you.
