### ISSUE TITLE
Incomplete verses and typos at SUV

### ISSUE THREAD

**Issue by okellogerald** [Bolls-Bible/bain#17]
https://bolls.life/SUV/47/6/2
This verse wasn't finished in the SUV translation.

Current verse:
_(Kwa maana asema, Wakati uliokubalika nalikusikia, Siku ya wokovu nalikusaidia;_

Expected Verse for SUV 1997 translation:
_(Kwa maana asema, Wakati uliokubalika nalikusikia, Siku ya wokovu nalikusaidia; tazama, wakati uliokubalika ndio sasa; tazama, siku ya wokovu ndiyo sasa.)_

Are you guys happy with fixing these kinds of issues?

**Comment by Bohooslav** [comment]
Man. Big thanks for the reporting. I guess you're reading daily. I feel like there are more typos in that translation and in order to avoid too often updates I wanna give you month or a few weeks to make a tiny collection of typos if you'll find them, and then I'll fix them in batch. Is it OK? If there is anything you need to BE fixed right now, because you have presentation or something I can make fix right now, no worries, just wanna make it easier for us.

**Comment by Bohooslav** [comment]
I feel sorry for low quality translation, I have what I have, can't really do anything about it without your help ❤️

**Comment by okellogerald** [comment]
Hello Bohuslav,

Sorry for the delayed response.

I am okay with grouping a bunch of misquotations if I will find them as I
continue using the app. I am finding your app really helpful and I am glad
that I am contributing to making it better, especially for the translations
that I am often using.

Thanks for putting together such a great app and releasing it to the public.

Hopefully I will have a chance to contribute to the project in the future.

Best regards,
Okello.

**Comment by Bohooslav** [comment]
Oh, thank you, much appreciated! ❤️‍🔥

**Comment by okellogerald** [comment]
I will be listing the ones I find here:

https://bolls.life/ESV/62/2/20/
Current: _Nanyi mmepakwa mafuta na Yeye aliye Mtakatifu nanyi mnajua *nyote*._
Expected: _Nanyi mmepakwa mafuta na Yeye aliye Mtakatifu nanyi mnajua *yote*._

**Comment by Bohooslav** [comment]
Just pushed a new version (v2.3.7) with verses above fixed.

**Comment by okellogerald** [comment]
Okay. Thanks.

**Comment by Bohooslav** [comment]
Glad there was no typos anymore 🙃

**Comment by Bohooslav** [comment]
Reopen if needed.
