### ISSUE TITLE
RSV2-CE possibly?

### ISSUE THREAD

**Issue by TomSipsOnCurry** [Bolls-Bible/bain#20]
Any plans to add the RSC2-CE, and possible more catholic translations as well (that include the deuterocanon).

**Comment by Bohooslav** [comment]
Yeah, sure will add today. About the deuterocanon -- there are a couple translations with it, like KJV with apocrypha or WEB.

**Comment by Bohooslav** [comment]
Just released it. Review the deployed translation and close the issue once done.
