### ISSUE TITLE
Add CUV Ukrainian translation

### ISSUE THREAD

**Issue by akdevservices** [Bolls-Bible/bain#21]
Add CUV Ukrainian translation, так званий новий сучасний переклад УБТ (Українського Біблійного Товариства), наскільки я зрозумів, це нова редакція переклада Турконяка, з виправленнями та де враховані багато зауважень.

Дякую за чудовий софт.

**Comment by Bohooslav** [comment]
Перевірте, і закрийте issue якшо все добре)
https://bolls.life/CUV23/1/1/

**Comment by akdevservices** [comment]
Є якісь незрозумілі індекси маленькими літерами латиною a, b, c після номерів віршів (див. прікріплений скріншот). А так наче відкривається і переклад той самий, співпадає з виданням 23 року, яке є в мене. Код перекладу CUV23 по року видання? Просто цікавість, ще є якийсь CUV але іншого року?

![image](https://github.com/user-attachments/assets/8437f351-36b8-4a77-9607-dac8e03bf431)

**Comment by Bohooslav** [comment]
Якшо маєш включені коментарі то побачиш шо ті індекси то мітки на які коментарі посилаються. Можу їх сховати коли вимкнуті коментарі.
Є один китайський переклад шо вже має абревіатуру CUV 
Назви книг такі і були, але можу поправити, якшо треба.

Якшо це все треба то відпишіть, та ввечері поправлю...

**Comment by akdevservices** [comment]
> Можу їх сховати коли вимкнуті коментарі.

Це буде те що треба.

> Назви книг такі і були, але можу поправити, якшо треба.

Будь-ласка, тому що важкувато читається перелік книг і всі (чи майже всі) інші переклади в додатку використовують формат "маленькими літерами, починаючи з великої".

Є ще трохи інших багів, але то зроблю якось окремими ишью.

**Comment by Bohooslav** [comment]
Баги? 🤨 Які баги? Ану сюда нв стул усіх 👇🏻!!!

**Comment by akdevservices** [comment]
Нічого суттєвого. Один з тих, що трохи дратують - самостійно скидається стандартний біблійний (нехронологічний) порядок книг. Трохи пізніше, ввечері чи на днях опишу.

**Comment by Bohooslav** [comment]
Я запушив фікс вчора ввечері, перевірте.

**Comment by akdevservices** [comment]
Все ОК. Дякую.
