### ISSUE TITLE
Feature request: custom theme(-s)

### ISSUE THREAD

**Issue by akdevservices** [Bolls-Bible/bain#25]
Add custom theme(-s) with a background color specified by the user.

**Comment by Bohooslav** [comment]
Any examples of use case? Why would you need that? You wanna bright salad font on top of a dark fried beef brown? What theme is missing among existing?

**Comment by akdevservices** [comment]
When using a smartphone in various lighting conditions, it is useful to have the option to make background darker or lighter. It could be a slider (darker/lighter) instead of a color chooser for the background. Anyway, it is a low priority suggestion.

**Comment by Bohooslav** [comment]
There are already two themes IMO perfect for any lightning conditions. Black and white. And I don't understand how slider may help with contrast issues? Doesn't smartphone have brightness regulation? Maybe you have a reference to a real world app that does it so that I may see what you mean.

**Comment by akdevservices** [comment]
> I don't understand how slider may help with contrast issues?

For instance, in low light conditions I'd prefer a dark grey as the background color instead of a black. This change has nothing to do with display brightness, it is needed to reduce the color contrast between the letter color and the background color. As we can't have themes suitable for everyone, it could be the slider that changes the background color shade (and another one for the letter shade?). You get the idea.

**Comment by Bohooslav** [comment]
It doesn't make sense to me. Pick the night theme which has dark bluish background and pinkish font, then lower your brightness if the contrast is too high. I cannot grasp how come high contrast may be an issue?!

**Comment by akdevservices** [comment]
> I cannot grasp how come high contrast may be an issue?!

Display contrast and color (or luminance) contrast of the particular image are two different things. For a brief explanation see https://gowripriyapadam.medium.com/why-using-pure-black-text-or-backgrounds-strain-eyes-ac20d871585c

**Comment by Bohooslav** [comment]
I have an idea of adding contrast slider that will make impact on all themes. Should be relatively easy and flexible.

**Comment by Bohooslav** [comment]
Would this satisfy you mr @akdevservices ?

https://github.com/user-attachments/assets/70cc8e2a-8d65-4934-a441-63d2344a115

**Comment by Bohooslav** [comment]
I think if you wanna decrease white color -- just lower your brightness.

**Comment by Bohooslav** [comment]
You said the key is at the relative difference between background and foreground. How does it matter where is top or bottom as long as the relative difference is good enough?

**Comment by akdevservices** [comment]
It's not just about the contrast, the absolute values of the colors matter for the user experience. Two images might seem similar, but a black background versus a gray one can make a difference. Imagine looking at them in a dark room or bright sunlight. The black background would be easier to see in the dark, while the gray one might be better in bright light. And trying to make the gray look black by adjusting the brightness is usually not going to work.

**Comment by Bohooslav** [comment]
![image](https://github.com/user-attachments/assets/8051fed2-32a8-4e0e-a259-c4bca6ab85e7)

This is 5

![image](https://github.com/user-attachments/assets/28b299bd-ffde-47bd-a076-637aebac75e5)
This is also 5

That's what I mean. One is relative, another is snapped to the white side.
Anyway, the way I have done it is that I just put a filter that literally changes the contrast. Sorry, but manipulating text and background separately is very complicated, and I won't have time for it. Hope the way I did it is good enough.

**Comment by Bohooslav** [comment]
Just pushed an update that provides the feature. Test it and see if it is any good enough...

**Comment by Bohooslav** [comment]
Hi, just wanted to thank you a lot for the request, I found myself as well having much easier time reading the Word at late night with rather lower contrast than default one. Thank you a lot!

**Comment by Bohooslav** [comment]
https://github.com/user-attachments/assets/4c7e3b8b-1838-4fa8-8d6e-cf09b16d2295

Just finally added what you asked for. Hope you'll enjoy it.
