### ISSUE TITLE
NABRE - Ezekiel Chapter 10-  When trying to read verses, app states the chapter does not exist 

### ISSUE THREAD

**Issue by AndyPandy1189** [Bolls-Bible/bain#26]
This is for both the API and the application, when looking for Ezekiel 10, it returns no data or declares that he chapter does not exist. 

![image](https://github.com/user-attachments/assets/4e8985fd-d66a-437e-a293-2971b060fc4f)

**Comment by Bohooslav** [comment]
1. What translation is it? Have you checked the same translation at other
resources? Is it the same? If not share with me references and I'll fix it.
Thanks for your time, Stay blessed!

**Comment by AndyPandy1189** [comment]
Hello!

It appears to just be the NABRE translation. For example, this shows for
the king James version (https://bolls.life/get-text/KJV/26/10/), but does
not show in the NABRE (https://bolls.life/get-text/NABRE/26/10/). I have
not exhaustively checked every translation though. I can confirm that this
by checking the chapter before and after it as well (
https://bolls.life/get-text/NABRE/26/9/ and
https://bolls.life/get-text/NABRE/26/11/ are both returning results.

Hope this helps!

AO

**Comment by Bohooslav** [comment]
![image](https://github.com/user-attachments/assets/9080a5c4-7bef-4cbd-9c56-ce457aafceb3)
This is a terrible mistake. I'll fix it asap. If you'll notice anything else, please let me know! Thanks for the report!

**Comment by AndyPandy1189** [comment]
No worries! Happy to help :)

**Comment by Bohooslav** [comment]
Should work now.

**Comment by Bohooslav** [comment]
@AndyPandy1189 have you been able to verify this? Please get back to me and close the issue once resolved

**Comment by AndyPandy1189** [comment]
Yes! Sorry I did verify after you corrected it. This is working now.

**Comment by Bohooslav** [comment]
Glad to help you. Sorry it took so long to communicate. Anyway, if the feature is done, please, close the Issue.

**Comment by AndyPandy1189** [comment]
Issue resolved on Aug 15th, thanks so much!
