### ISSUE TITLE
For NABRE translation, it is missing the Book of Wisdom

### ISSUE THREAD

**Issue by AndyPandy1189** [Bolls-Bible/bain#28]
NABRE is a Catholic translation of the bible and has some additional books that appear to be missing from the bible. The Book of Wisdom appears to be one of these books. There are others, such as Tobit, that also appear to be missing.

**Comment by Bohooslav** [comment]
And? What is the problem and what solution do you suppose?
Are you talking about [this book of Wisdom](http://bolls.local/NABRE/70/1/) and [this book of Tobit](http://bolls.local/NABRE/68/1/)?

**Comment by AndyPandy1189** [comment]
Yes and I'm so sorry, you do actually have them. They are listed in the New testament books, but these are actually old testament books. This is why I did not see them. My apologies! I'll close this issue.

**Comment by Bohooslav** [comment]
I am sorry, but this is my fault in terms of architectural design. But I can fix it. I can add a new splitter, like the one in between OT and NT, and indicate by it that NT ends and apocrypha begins?
