### ISSUE TITLE
Add another Ukrainian translation (Popchenko)

### ISSUE THREAD

**Issue by akdevservices** [Bolls-Bible/bain#35]
Якщо можливо, прошу додати переклад Нового Завіту Ю. Попченком.

**Comment by Bohooslav** [comment]
Можу, і добавлю в неділю.

**Comment by akdevservices** [comment]
Супер, дякую!

**Comment by akdevservices** [comment]
Я тільки що усвідомив, що якщо додати переклади Нового Завіту Деркача (-ів) і український переклад Біблії Громова, то додаток буде мати практично повний набір вживаних на цей момент перекладів! Якщо я не помиляюсь, інших таких додатків станом на зараз просто нема.

**Comment by Bohooslav** [comment]
@akdevservices можу додати любий переклад з цього списку. https://www.ph4.org/b4_1.php?l=uk

**Comment by akdevservices** [comment]
> @akdevservices можу додати любий переклад з цього списку. https://www.ph4.org/b4_1.php?l=uk

- Попч 2020 (Новий Завіт в перекладі Попченка)
- UKDER 1992 (Новий Завіт + Псалми + Притчи в перекладі Деркачів). Цей переклад схожий на переклад Філарета, тобто не з мов оригіналу (давньоєврейська, арамейська, давньогрецька, септуагінта і т.д.), але він добре читається і, кажуть, непоганий (я не читав).
- GYZ 2006 (переклад Біблії Гижі). Це є своєрідна компіляція інших перекладів через призму ХВЄ, тобто пятидесятників). Але він непогано читається і його теж можна додати.

Перекладу Громова тут, нажаль, немає. Це один з найбільш цікавих перекладів, він доволі точний, сучасною мовою, але розповсюджується наче лише через сайт автора і лише в преміальному дорогому варіанті. Якщо знайдете переклади Громова (і російською також) - їх однозначно варто додати, але я не знаю, що там з авторськими правами, тому що схема розповсюдження натякає.

**Comment by akdevservices** [comment]
Якщо ви ще додасте ці доволі відомі і популярні англійські переклади, буде чудово:
- CEB 2011
- CEV 2006
- CSB 2017

**Comment by Bohooslav** [comment]
Постараюся, але вже не вийдесьогодні.

**Comment by akdevservices** [comment]
Це лише побажання, не більше. І в нинішньому вигляді додатки роблять що треба.

**Comment by Bohooslav** [comment]
@akdevservices Я додав названі переклади, будь ласка, перевірте і дайте знати чи все добре!

**Comment by akdevservices** [comment]
@Bohooslav Всі переклади є. Дякую! Ви зробили велику справу.
На перший погляд:
- в перекладі Гижі частини деяких віршів чомусь виділені жирним шрифтом. Наприклад, Буття 1:27,31
- в деяких англійських перекладах (не тільки в 3 доданих тільки що, а і в доданих раніше) є незрозуміле форматування і помилки. Наприклад, NABRE, NLT, NIV і т. д. John 5:4 вірш взагалі пустий. CSB17 John 1:23, NET John 1:23 частина вірша виділена жирним. Чи John розділ 1 (NABRE, CEVD, CEB, NLT і т. д.) збите форматування - великі проміжки між віршами, примусові завчасні переноси слів на наступний рядок, тобто рядки не заповнені повністю і подібне.

**Comment by Bohooslav** [comment]
1. В перекладі Гижі так і має бути.
2. А це суто форматування, треба переглянути. В багатьох перекладах деякі вірші разом збиті, або їх взагалі нема в манускриптах які вони використовували, тому може скластися враження що там чогось не хватає, але так і має бути.

**Comment by akdevservices** [comment]
> В перекладі Гижі так і має бути.

1. Я не зовсім зрозумів, за яким принципом окремі частини віршів виділені жирним.
2. Добре, на днях викладу приклади.

**Comment by Bohooslav** [comment]
Ну як було жирним в тексті який я брав -- так я і лишив. 🤷🏼‍♂️
