### ISSUE TITLE
iOS App

### ISSUE THREAD

**Issue by meichthys** [Bolls-Bible/bain#9]
First of all, I'm very impressed with this app and can't believe i didn't come across it sooner. The fact that you offer a docker-compose file is amazing!

I'm curious to see if it would be possible to build an iOS app for this. I'm not too familiar with Electron to know if this would be feasible.

**Comment by Bohooslav** [comment]
You can do a webview and load bolls.life there. It will work as PWA. I tried it over 3 years ago, it worked back then and because of lack of money, mackbook and potential issues with Apples I didn't release it.
https://github.com/Bohooslav/bolls-ios
